#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated On: 16-4-2019 10:02
# Generated By: bhuygen
# his code was written by Bas Huygen, member of the Data Analytics team named Orion of KPN B.V.
#    Build june - september 2018
#   v0.18 dec 2018 - addition of interfaces Database Ports
#    v0.19 jan 2019 - addition of interface DatabaseRelations
#    v0.20 feb 2019 - add clear testset button, reworked checkbox to clear uniqueness
#    v0.25 feb 2019 - rebuild of system into GUI script and modules for each interface
#    v0.30 apr 2019 - Complete rebuild of GUI to include relational interfaces in a new tab
#    v0.32 apr 2019 - Added comment to the main script
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$TestSetBuilder = New-Object System.Windows.Forms.Form
$Main = New-Object System.Windows.Forms.TabControl
$tabPage1 = New-Object System.Windows.Forms.TabPage
$lbldisclaimer = New-Object System.Windows.Forms.Label
$Control_panel = New-Object System.Windows.Forms.Panel
$ButtonRemovePrevious = New-Object System.Windows.Forms.Button
$ButtonClear = New-Object System.Windows.Forms.Button
$ltsprogress = New-Object System.Windows.Forms.ListBox
$lblProgressBar = New-Object System.Windows.Forms.Label
$progressBar = New-Object System.Windows.Forms.ProgressBar
$lblInterface = New-Object System.Windows.Forms.Label
$cmbInterface = New-Object System.Windows.Forms.ComboBox
$Input_Panel = New-Object System.Windows.Forms.Panel
$lblAmount = New-Object System.Windows.Forms.Label
$txbRecords = New-Object System.Windows.Forms.TextBox
$txbnok = New-Object System.Windows.Forms.TextBox
$lblUpdates = New-Object System.Windows.Forms.Label
$lblnok = New-Object System.Windows.Forms.Label
$txbupdates = New-Object System.Windows.Forms.TextBox
$txbNew = New-Object System.Windows.Forms.TextBox
$lblnew = New-Object System.Windows.Forms.Label
$Output_panel = New-Object System.Windows.Forms.Panel
$chbClearUniqueness = New-Object System.Windows.Forms.CheckBox
$txbOutPath = New-Object System.Windows.Forms.TextBox
$lblOutPath = New-Object System.Windows.Forms.Label
$lblOpenTestset = New-Object System.Windows.Forms.Label
$lblLogfile = New-Object System.Windows.Forms.Label
$ButtonStart = New-Object System.Windows.Forms.Button
$tabPage2 = New-Object System.Windows.Forms.TabPage
$Rel_output_panel = New-Object System.Windows.Forms.Panel
$lblRelOutputpath = New-Object System.Windows.Forms.Label
$lblRelopenset = New-Object System.Windows.Forms.Label
$lblRellog = New-Object System.Windows.Forms.Label
$btnRelStart = New-Object System.Windows.Forms.Button
$Rel_control_panel = New-Object System.Windows.Forms.Panel
$btnRelRemoveTestset = New-Object System.Windows.Forms.Button
$btnRelclear = New-Object System.Windows.Forms.Button
$lstRelProgress = New-Object System.Windows.Forms.ListBox
$lblRelProgress = New-Object System.Windows.Forms.Label
$RelprogressBar = New-Object System.Windows.Forms.ProgressBar
$Rel_input_panel = New-Object System.Windows.Forms.Panel
$txbRelNan = New-Object System.Windows.Forms.TextBox
$txbRelRec = New-Object System.Windows.Forms.TextBox
$lblrelrec = New-Object System.Windows.Forms.Label
$lblRelNan = New-Object System.Windows.Forms.Label
$txbRelDeletes = New-Object System.Windows.Forms.TextBox
$lblRelDeletes = New-Object System.Windows.Forms.Label
$txbRelCreate = New-Object System.Windows.Forms.TextBox
$lblRelCreate = New-Object System.Windows.Forms.Label
$cmbRelInterface = New-Object System.Windows.Forms.ComboBox
$lbl_rel_interface = New-Object System.Windows.Forms.Label
$tabPage3 = New-Object System.Windows.Forms.TabPage
$lblSource1 = New-Object System.Windows.Forms.Label
$txbSource1 = New-Object System.Windows.Forms.TextBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------


$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$TestSetBuilder.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 550
$System_Drawing_Size.Width = 782
$TestSetBuilder.ClientSize = $System_Drawing_Size
$TestSetBuilder.DataBindings.DefaultDataSourceUpdateMode = 0
$TestSetBuilder.Name = "TestSetBuilder"
$TestSetBuilder.Text = "TestSet Builder v0.32"

$Main.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 2
$Main.Location = $System_Drawing_Point
$Main.Name = "Main"
$Main.SelectedIndex = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 536
$System_Drawing_Size.Width = 758
$Main.Size = $System_Drawing_Size
$Main.TabIndex = 0
$Main.add_SelectedIndexChanged($handler__SelectedIndexChanged)

$TestSetBuilder.Controls.Add($Main)
$tabPage1.BackColor = [System.Drawing.Color]::FromArgb(255,220,220,220)
$tabPage1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$tabPage1.Location = $System_Drawing_Point
$tabPage1.Name = "tabPage1"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$tabPage1.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 510
$System_Drawing_Size.Width = 750
$tabPage1.Size = $System_Drawing_Size
$tabPage1.TabIndex = 0
$tabPage1.Text = "Standard Interface"
$tabPage1.add_Click($handler_TabPage:_Click)

$Main.Controls.Add($tabPage1)
$lbldisclaimer.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 474
$lbldisclaimer.Location = $System_Drawing_Point
$lbldisclaimer.Name = "lbldisclaimer"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 277
$lbldisclaimer.Size = $System_Drawing_Size
$lbldisclaimer.TabIndex = 15
$lbldisclaimer.Text = "Copyright KPN B.V.  Build by Bas Huygen KPN "
$lbldisclaimer.add_Click($handler_label10_Click)

$tabPage1.Controls.Add($lbldisclaimer)


$Control_panel.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 289
$System_Drawing_Point.Y = 11
$Control_panel.Location = $System_Drawing_Point
$Control_panel.Name = "Control_panel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 263
$System_Drawing_Size.Width = 452
$Control_panel.Size = $System_Drawing_Size
$Control_panel.TabIndex = 17
$Control_panel.add_Paint($handler_Control_Paint)

$tabPage1.Controls.Add($Control_panel)

$ButtonRemovePrevious.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 146
$System_Drawing_Point.Y = 194
$ButtonRemovePrevious.Location = $System_Drawing_Point
$ButtonRemovePrevious.Name = "ButtonRemovePrevious"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 52
$System_Drawing_Size.Width = 89
$ButtonRemovePrevious.Size = $System_Drawing_Size
$ButtonRemovePrevious.TabIndex = 8
$ButtonRemovePrevious.Text = "Remove Testset"
$ButtonRemovePrevious.UseVisualStyleBackColor = $True
$ButtonRemovePrevious.add_Click($handler_button3_Click)

$Control_panel.Controls.Add($ButtonRemovePrevious)


$ButtonClear.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 39
$System_Drawing_Point.Y = 194
$ButtonClear.Location = $System_Drawing_Point
$ButtonClear.Name = "ButtonClear"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 52
$System_Drawing_Size.Width = 89
$ButtonClear.Size = $System_Drawing_Size
$ButtonClear.TabIndex = 7
$ButtonClear.Text = "Clear Progress screen"
$ButtonClear.UseVisualStyleBackColor = $True
$ButtonClear.add_Click($handler_button2_Click)

$Control_panel.Controls.Add($ButtonClear)

$ltsprogress.DataBindings.DefaultDataSourceUpdateMode = 0
$ltsprogress.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 39
$System_Drawing_Point.Y = 71
$ltsprogress.Location = $System_Drawing_Point
$ltsprogress.Name = "ltsprogress"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 108
$System_Drawing_Size.Width = 373
$ltsprogress.Size = $System_Drawing_Size
$ltsprogress.TabIndex = 10
$ltsprogress.add_SelectedIndexChanged($handler_listBox1_SelectedIndexChanged)

$Control_panel.Controls.Add($ltsprogress)

$lblProgressBar.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 39
$System_Drawing_Point.Y = 16
$lblProgressBar.Location = $System_Drawing_Point
$lblProgressBar.Name = "lblProgressBar"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblProgressBar.Size = $System_Drawing_Size
$lblProgressBar.TabIndex = 1
$lblProgressBar.Text = "Progress"
$lblProgressBar.add_Click($handler_label9_Click)

$Control_panel.Controls.Add($lblProgressBar)

$progressBar.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 39
$System_Drawing_Point.Y = 42
$progressBar.Location = $System_Drawing_Point
$progressBar.Name = "progressBar"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 373
$progressBar.Size = $System_Drawing_Size
$progressBar.TabIndex = 9
$progressBar.add_Click($handler_progressBar2_Click)

$Control_panel.Controls.Add($progressBar)


$lblInterface.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 27
$System_Drawing_Point.Y = 27
$lblInterface.Location = $System_Drawing_Point
$lblInterface.Name = "lblInterface"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblInterface.Size = $System_Drawing_Size
$lblInterface.TabIndex = 2
$lblInterface.Text = "Choose Interface"
$lblInterface.add_Click($handler_label1_Click)

$tabPage1.Controls.Add($lblInterface)

$cmbInterface.DataBindings.DefaultDataSourceUpdateMode = 0
$cmbInterface.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 27
$System_Drawing_Point.Y = 61
$cmbInterface.Location = $System_Drawing_Point
$cmbInterface.Name = "cmbInterface"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 121
$cmbInterface.Size = $System_Drawing_Size
$cmbInterface.TabIndex = 1
$cmbInterface.Text = "Interface"
$cmbInterface.add_SelectedIndexChanged($handler_comboBox1_SelectedIndexChanged)

$tabPage1.Controls.Add($cmbInterface)


$Input_Panel.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 11
$Input_Panel.Location = $System_Drawing_Point
$Input_Panel.Name = "Input_Panel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 439
$System_Drawing_Size.Width = 246
$Input_Panel.Size = $System_Drawing_Size
$Input_Panel.TabIndex = 16
$Input_Panel.add_Paint($handler_Input_Paint)

$tabPage1.Controls.Add($Input_Panel)
$lblAmount.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 89
$lblAmount.Location = $System_Drawing_Point
$lblAmount.Name = "lblAmount"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 185
$lblAmount.Size = $System_Drawing_Size
$lblAmount.TabIndex = 3
$lblAmount.Text = "Number of records each source"
$lblAmount.add_Click($handler_label2_Click)

$Input_Panel.Controls.Add($lblAmount)

$txbRecords.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 115
$txbRecords.Location = $System_Drawing_Point
$txbRecords.Name = "txbRecords"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txbRecords.Size = $System_Drawing_Size
$txbRecords.TabIndex = 2
$txbRecords.Text = 0
$txbRecords.add_TextChanged($handler_textBox1_TextChanged)

$Input_Panel.Controls.Add($txbRecords)

$txbnok.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 360
$txbnok.Location = $System_Drawing_Point
$txbnok.Name = "txbnok"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txbnok.Size = $System_Drawing_Size
$txbnok.TabIndex = 5
$txbnok.Text = 0
$txbnok.add_TextChanged($handler_textBox4_TextChanged)

$Input_Panel.Controls.Add($txbnok)

$lblUpdates.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 156
$lblUpdates.Location = $System_Drawing_Point
$lblUpdates.Name = "lblUpdates"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 185
$lblUpdates.Size = $System_Drawing_Size
$lblUpdates.TabIndex = 5
$lblUpdates.Text = "Number of updates each source"
$lblUpdates.add_Click($handler_label3_Click)

$Input_Panel.Controls.Add($lblUpdates)

$lblnok.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 317
$lblnok.Location = $System_Drawing_Point
$lblnok.Name = "lblnok"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblnok.Size = $System_Drawing_Size
$lblnok.TabIndex = 9
$lblnok.Text = "Number of NOK each source"
$lblnok.add_Click($handler_label5_Click)

$Input_Panel.Controls.Add($lblnok)

$txbupdates.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 194
$txbupdates.Location = $System_Drawing_Point
$txbupdates.Name = "txbupdates"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txbupdates.Size = $System_Drawing_Size
$txbupdates.TabIndex = 3
$txbupdates.Text = 0
$txbupdates.add_TextChanged($handler_textBox2_TextChanged)

$Input_Panel.Controls.Add($txbupdates)

$txbNew.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 277
$txbNew.Location = $System_Drawing_Point
$txbNew.Name = "txbNew"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txbNew.Size = $System_Drawing_Size
$txbNew.TabIndex = 4
$txbNew.Text = 0
$txbNew.add_TextChanged($handler_textBox3_TextChanged)

$Input_Panel.Controls.Add($txbNew)

$lblnew.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 240
$lblnew.Location = $System_Drawing_Point
$lblnew.Name = "lblnew"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 185
$lblnew.Size = $System_Drawing_Size
$lblnew.TabIndex = 7
$lblnew.Text = "Number of New records each source"
$lblnew.add_Click($handler_label4_Click)

$Input_Panel.Controls.Add($lblnew)



$Output_panel.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 289
$System_Drawing_Point.Y = 288
$Output_panel.Location = $System_Drawing_Point
$Output_panel.Name = "Output_panel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 184
$System_Drawing_Size.Width = 452
$Output_panel.Size = $System_Drawing_Size
$Output_panel.TabIndex = 18
$Output_panel.add_Paint($handler_Output_Paint)

$tabPage1.Controls.Add($Output_panel)

$chbClearUniqueness.Checked = $True
$chbClearUniqueness.CheckState = 1
$chbClearUniqueness.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 283
$System_Drawing_Point.Y = 12
$chbClearUniqueness.Location = $System_Drawing_Point
$chbClearUniqueness.Name = "chbClearUniqueness"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 143
$chbClearUniqueness.Size = $System_Drawing_Size
$chbClearUniqueness.TabIndex = 15
$chbClearUniqueness.Text = "Clear File Uniqueness"
$chbClearUniqueness.UseVisualStyleBackColor = $True
$chbClearUniqueness.add_CheckedChanged($handler_checkBox1_CheckedChanged)

$Output_panel.Controls.Add($chbClearUniqueness)

$txbOutPath.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 28
$System_Drawing_Point.Y = 137
$txbOutPath.Location = $System_Drawing_Point
$txbOutPath.Name = "txbOutPath"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 225
$txbOutPath.Size = $System_Drawing_Size
$txbOutPath.TabIndex = 14
$txbOutPath.Text = "O:\Testsets"
$txbOutPath.add_TextChanged($handler_textBox5_TextChanged)

$Output_panel.Controls.Add($txbOutPath)

$lblOutPath.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 28
$System_Drawing_Point.Y = 111
$lblOutPath.Location = $System_Drawing_Point
$lblOutPath.Name = "lblOutPath"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblOutPath.Size = $System_Drawing_Size
$lblOutPath.TabIndex = 13
$lblOutPath.Text = "Output Path"
$lblOutPath.add_Click($handler_label8_Click)

$Output_panel.Controls.Add($lblOutPath)

$lblOpenTestset.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 28
$System_Drawing_Point.Y = 42
$lblOpenTestset.Location = $System_Drawing_Point
$lblOpenTestset.Name = "lblOpenTestset"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblOpenTestset.Size = $System_Drawing_Size
$lblOpenTestset.TabIndex = 12
$lblOpenTestset.Text = "Open Testset"
$lblOpenTestset.add_Click($handler_label7_Click)

$Output_panel.Controls.Add($lblOpenTestset)

$lblLogfile.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 28
$System_Drawing_Point.Y = 17
$lblLogfile.Location = $System_Drawing_Point
$lblLogfile.Name = "lblLogfile"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblLogfile.Size = $System_Drawing_Size
$lblLogfile.TabIndex = 11
$lblLogfile.Text = "Open Logfile"
$lblLogfile.add_Click($handler_label6_Click)

$Output_panel.Controls.Add($lblLogfile)


$ButtonStart.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 283
$System_Drawing_Point.Y = 42
$ButtonStart.Location = $System_Drawing_Point
$ButtonStart.Name = "ButtonStart"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 115
$System_Drawing_Size.Width = 157
$ButtonStart.Size = $System_Drawing_Size
$ButtonStart.TabIndex = 6
$ButtonStart.Text = "Start"
$ButtonStart.UseVisualStyleBackColor = $True
$ButtonStart.add_Click($handler_btnStart_Click)

$Output_panel.Controls.Add($ButtonStart)



$tabPage2.BackColor = [System.Drawing.Color]::FromArgb(255,211,211,211)
$tabPage2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$tabPage2.Location = $System_Drawing_Point
$tabPage2.Name = "tabPage2"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$tabPage2.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 510
$System_Drawing_Size.Width = 750
$tabPage2.Size = $System_Drawing_Size
$tabPage2.TabIndex = 1
$tabPage2.Text = "Relations Interface"
$tabPage2.add_Click($handler_TabPage:_Click)

$Main.Controls.Add($tabPage2)

$Rel_output_panel.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 320
$System_Drawing_Point.Y = 266
$Rel_output_panel.Location = $System_Drawing_Point
$Rel_output_panel.Name = "Rel_output_panel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 201
$System_Drawing_Size.Width = 406
$Rel_output_panel.Size = $System_Drawing_Size
$Rel_output_panel.TabIndex = 2
$Rel_output_panel.add_Paint($handler_Rel_output_panel_Paint)

$tabPage2.Controls.Add($Rel_output_panel)
$lblRelOutputpath.DataBindings.DefaultDataSourceUpdateMode = 0
$lblRelOutputpath.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 128
$lblRelOutputpath.Location = $System_Drawing_Point
$lblRelOutputpath.Name = "lblRelOutputpath"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 40
$System_Drawing_Size.Width = 218
$lblRelOutputpath.Size = $System_Drawing_Size
$lblRelOutputpath.TabIndex = 3
$lblRelOutputpath.Text = "Set Output path on Standard Interface tab"
$lblRelOutputpath.add_Click($handler_lblRelOutputpath_Click)

$Rel_output_panel.Controls.Add($lblRelOutputpath)

$lblRelopenset.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 67
$lblRelopenset.Location = $System_Drawing_Point
$lblRelopenset.Name = "lblRelopenset"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblRelopenset.Size = $System_Drawing_Size
$lblRelopenset.TabIndex = 2
$lblRelopenset.Text = "Open testset"
$lblRelopenset.add_Click($handler_lblRelopenset_Click)

$Rel_output_panel.Controls.Add($lblRelopenset)

$lblRellog.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 28
$lblRellog.Location = $System_Drawing_Point
$lblRellog.Name = "lblRellog"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblRellog.Size = $System_Drawing_Size
$lblRellog.TabIndex = 1
$lblRellog.Text = "Open logfile"
$lblRellog.add_Click($handler_lblRellog_Click)

$Rel_output_panel.Controls.Add($lblRellog)


$btnRelStart.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 249
$System_Drawing_Point.Y = 80
$btnRelStart.Location = $System_Drawing_Point
$btnRelStart.Name = "btnRelStart"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 103
$System_Drawing_Size.Width = 143
$btnRelStart.Size = $System_Drawing_Size
$btnRelStart.TabIndex = 6
$btnRelStart.Text = "Start"
$btnRelStart.UseVisualStyleBackColor = $True
$btnRelStart.add_Click($handler_btnRelStart_Click)

$Rel_output_panel.Controls.Add($btnRelStart)



$Rel_control_panel.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 320
$System_Drawing_Point.Y = 18
$Rel_control_panel.Location = $System_Drawing_Point
$Rel_control_panel.Name = "Rel_control_panel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 227
$System_Drawing_Size.Width = 406
$Rel_control_panel.Size = $System_Drawing_Size
$Rel_control_panel.TabIndex = 1
$Rel_control_panel.add_Paint($handler_Rel_control_panel_Paint)

$tabPage2.Controls.Add($Rel_control_panel)

$btnRelRemoveTestset.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 138
$System_Drawing_Point.Y = 175
$btnRelRemoveTestset.Location = $System_Drawing_Point
$btnRelRemoveTestset.Name = "btnRelRemoveTestset"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 48
$System_Drawing_Size.Width = 95
$btnRelRemoveTestset.Size = $System_Drawing_Size
$btnRelRemoveTestset.TabIndex = 4
$btnRelRemoveTestset.Text = "Remove Testset"
$btnRelRemoveTestset.UseVisualStyleBackColor = $True
$btnRelRemoveTestset.add_Click($handler_btnRelRemoveTestset_Click)

$Rel_control_panel.Controls.Add($btnRelRemoveTestset)


$btnRelclear.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 175
$btnRelclear.Location = $System_Drawing_Point
$btnRelclear.Name = "btnRelclear"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 48
$System_Drawing_Size.Width = 107
$btnRelclear.Size = $System_Drawing_Size
$btnRelclear.TabIndex = 3
$btnRelclear.Text = "Clear Progress screen"
$btnRelclear.UseVisualStyleBackColor = $True
$btnRelclear.add_Click($handler_btnRelclear_Click)

$Rel_control_panel.Controls.Add($btnRelclear)

$lstRelProgress.DataBindings.DefaultDataSourceUpdateMode = 0
$lstRelProgress.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 74
$lstRelProgress.Location = $System_Drawing_Point
$lstRelProgress.Name = "lstRelProgress"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 95
$System_Drawing_Size.Width = 377
$lstRelProgress.Size = $System_Drawing_Size
$lstRelProgress.TabIndex = 2
$lstRelProgress.add_SelectedIndexChanged($handler_lstRelProgress_SelectedIndexChanged)

$Rel_control_panel.Controls.Add($lstRelProgress)

$lblRelProgress.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 12
$lblRelProgress.Location = $System_Drawing_Point
$lblRelProgress.Name = "lblRelProgress"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblRelProgress.Size = $System_Drawing_Size
$lblRelProgress.TabIndex = 1
$lblRelProgress.Text = "Progress"
$lblRelProgress.add_Click($handler_lblRelProgress_Click)

$Rel_control_panel.Controls.Add($lblRelProgress)

$RelprogressBar.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 36
$RelprogressBar.Location = $System_Drawing_Point
$RelprogressBar.Name = "RelprogressBar"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 377
$RelprogressBar.Size = $System_Drawing_Size
$RelprogressBar.TabIndex = 0
$RelprogressBar.add_Click($handler_RelprogressBar_Click)

$Rel_control_panel.Controls.Add($RelprogressBar)



$Rel_input_panel.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 17
$System_Drawing_Point.Y = 18
$Rel_input_panel.Location = $System_Drawing_Point
$Rel_input_panel.Name = "Rel_input_panel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 449
$System_Drawing_Size.Width = 271
$Rel_input_panel.Size = $System_Drawing_Size
$Rel_input_panel.TabIndex = 0
$Rel_input_panel.add_Paint($handler_Rel_input_panel_Paint)

$tabPage2.Controls.Add($Rel_input_panel)
$txbRelNan.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 328
$txbRelNan.Location = $System_Drawing_Point
$txbRelNan.Name = "txbRelNan"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txbRelNan.Size = $System_Drawing_Size
$txbRelNan.TabIndex = 5
$txbRelNan.Text = 0
$txbRelNan.add_TextChanged($handler_txbRelNan_TextChanged)

$Rel_input_panel.Controls.Add($txbRelNan)

$txbRelRec.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 101
$txbRelRec.Location = $System_Drawing_Point
$txbRelRec.Name = "txbRelRec"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txbRelRec.Size = $System_Drawing_Size
$txbRelRec.TabIndex = 2
$txbRelRec.Text = 0
$txbRelRec.add_TextChanged($handler_txbRelRec_TextChanged)

$Rel_input_panel.Controls.Add($txbRelRec)

$lblrelrec.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 74
$lblrelrec.Location = $System_Drawing_Point
$lblrelrec.Name = "lblrelrec"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 174
$lblrelrec.Size = $System_Drawing_Size
$lblrelrec.TabIndex = 7
$lblrelrec.Text = "Number of records each source"
$lblrelrec.add_Click($handler_lblrelrec_Click)

$Rel_input_panel.Controls.Add($lblrelrec)

$lblRelNan.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 290
$lblRelNan.Location = $System_Drawing_Point
$lblRelNan.Name = "lblRelNan"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 148
$lblRelNan.Size = $System_Drawing_Size
$lblRelNan.TabIndex = 6
$lblRelNan.Text = "Number of NAN each source"
$lblRelNan.add_Click($handler_lblRelNan_Click)

$Rel_input_panel.Controls.Add($lblRelNan)

$txbRelDeletes.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 248
$txbRelDeletes.Location = $System_Drawing_Point
$txbRelDeletes.Name = "txbRelDeletes"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txbRelDeletes.Size = $System_Drawing_Size
$txbRelDeletes.TabIndex = 4
$txbRelDeletes.Text = 0
$txbRelDeletes.add_TextChanged($handler_txbRelDeletes_TextChanged)

$Rel_input_panel.Controls.Add($txbRelDeletes)

$lblRelDeletes.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 215
$lblRelDeletes.Location = $System_Drawing_Point
$lblRelDeletes.Name = "lblRelDeletes"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 165
$lblRelDeletes.Size = $System_Drawing_Size
$lblRelDeletes.TabIndex = 4
$lblRelDeletes.Text = "Number of delete each source"
$lblRelDeletes.add_Click($handler_lblRelDeletes_Click)

$Rel_input_panel.Controls.Add($lblRelDeletes)

$txbRelCreate.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 170
$txbRelCreate.Location = $System_Drawing_Point
$txbRelCreate.Name = "txbRelCreate"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txbRelCreate.Size = $System_Drawing_Size
$txbRelCreate.TabIndex = 3
$txbRelCreate.Text = 0
$txbRelCreate.add_TextChanged($handler_txbRelCreate_TextChanged)

$Rel_input_panel.Controls.Add($txbRelCreate)

$lblRelCreate.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 143
$lblRelCreate.Location = $System_Drawing_Point
$lblRelCreate.Name = "lblRelCreate"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 174
$lblRelCreate.Size = $System_Drawing_Size
$lblRelCreate.TabIndex = 2
$lblRelCreate.Text = "Number of create each source"
$lblRelCreate.add_Click($handler_lblRelCreate_Click)

$Rel_input_panel.Controls.Add($lblRelCreate)

$cmbRelInterface.DataBindings.DefaultDataSourceUpdateMode = 0
$cmbRelInterface.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 38
$cmbRelInterface.Location = $System_Drawing_Point
$cmbRelInterface.Name = "cmbRelInterface"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 121
$cmbRelInterface.Size = $System_Drawing_Size
$cmbRelInterface.TabIndex = 1
$cmbRelInterface.Text = "Interface"
$cmbRelInterface.add_SelectedIndexChanged($handler_cmbRelInterface_SelectedIndexChanged)

$Rel_input_panel.Controls.Add($cmbRelInterface)

$lbl_rel_interface.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 12
$lbl_rel_interface.Location = $System_Drawing_Point
$lbl_rel_interface.Name = "lbl_rel_interface"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lbl_rel_interface.Size = $System_Drawing_Size
$lbl_rel_interface.TabIndex = 0
$lbl_rel_interface.Text = "Choose Interface"
$lbl_rel_interface.add_Click($handler_lbl_rel_interface_Click)

$Rel_input_panel.Controls.Add($lbl_rel_interface)



$tabPage3.BackColor = [System.Drawing.Color]::FromArgb(255,192,192,192)
$tabPage3.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$tabPage3.Location = $System_Drawing_Point
$tabPage3.Name = "tabPage3"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$tabPage3.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 510
$System_Drawing_Size.Width = 750
$tabPage3.Size = $System_Drawing_Size
$tabPage3.TabIndex = 2
$tabPage3.Text = "Source Definitions"
$tabPage3.add_Click($handler_TabPage:_Click)

$Main.Controls.Add($tabPage3)
$lblSource1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 45
$lblSource1.Location = $System_Drawing_Point
$lblSource1.Name = "lblSource1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lblSource1.Size = $System_Drawing_Size
$lblSource1.TabIndex = 1
$lblSource1.Text = "Header Sourcefile"
$lblSource1.add_Click($handler_lblSource1_Click)

$tabPage3.Controls.Add($lblSource1)

$txbSource1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 82
$txbSource1.Location = $System_Drawing_Point
$txbSource1.Name = "txbSource1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 669
$txbSource1.Size = $System_Drawing_Size
$txbSource1.TabIndex = 0
$txbSource1.add_TextChanged($handler_txbSource1_TextChanged)

$tabPage3.Controls.Add($txbSource1)

#prepopulate combobox interface
$cmbInterface.Items.Add('Computer') > $null
$cmbInterface.Items.Add('Computer_peripheral') > $null
$cmbInterface.Items.Add('Database') > $null
$cmbInterface.Items.Add('KPN_Werkplek') > $null
$cmbInterface.Items.Add('Networkgear') > $null
$cmbInterface.Items.Add('Ports') > $null
$cmbInterface.Items.Add('Printers') > $null
$cmbInterface.Items.Add('Server') > $null
$cmbInterface.Items.Add('Software') > $null
$cmbRelInterface.Items.Add('DatabaseRelations') > $null
$cmbRelInterface.Items.Add('SoftwareRelations') > $null

#region gui events {
$ButtonStart.Add_Click({ call_start })
$btnRelStart.Add_Click({ call_rel_start })
$ButtonClear.Add_Click({ call_clearprogress })
$ButtonRemovePrevious.Add_Click({ Remove_previous_testset  })
$btnRelclear.Add_Click({ call_clearprogress })
$btnRelRemoveTestset.Add_Click({ Remove_previous_reltestset  })
$lblLogfile.Add_Click({ open_logfile })
$lblRellog.Add_Click({ open_logfile })
$lblOpenTestset.Add_Click({ Open_testset })
$lblRelopenset.Add_Click({ Open_reltestset })
#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $TestSetBuilder.WindowState
#Init the OnLoad event to correct the initial state of the form
$TestSetBuilder.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$TestSetBuilder.ShowDialog()| Out-Null

} #End Function


# Main script code
Param(
    [Parameter(Mandatory=$True,Position=1)]
    [ValidateSet('Computer','Computer_Peripheral','Database','DatabaseRelations','KPN_Werkplek','Networkgear','Ports','Printers','Server','Software','Software_Relations')]
    [string]$SourceInterface,
    [Parameter(Mandatory=$False)]
    [ValidateSet('Yes','No')]
    [string]$ModifyDate,
    [Parameter(Mandatory=$False)]
    [ValidateSet('Yes','No')]
    [string]$Depersonalize,
    [Parameter(Mandatory=$False)]
    [int]$amount,
    [Parameter(Mandatory=$False)]
    [int]$AmountUpdates,
    [Parameter(Mandatory=$true)]
    [int]$AmountNew,
    [Parameter(Mandatory=$true)]
    [int]$AmountNOK
 )
 cls

#Define global variables
#$ErrorActionPreference= "Silentlycontinue"
$logdate=  Get-Date -Format "MM/dd/yyyy"
$dateshort= Get-Date -Format "dd-MM-yyyy"
$altdatelong= Get-Date -Format "yyyy-MM-dd hh:mm:ss"
$altaltdatelong= Get-Date -Format "MM/dd/yyyy hh:mm:ss"
$altdateshort= Get-Date -Format "yyyy-MM-dd"
$altdateHorus= Get-Date -Format "dd-MM-yyyy hh:mm"
$today=Get-Date -Format D
$Temp = (Get-date).AddDays(-7)
$sevendaysago=Get-Date $Temp -Format MM/dd/yyyy
$longtoday= Get-Date -Format dd/MM/yyyy/hh/mm
$uniquedatetime= (Get-Date -Format yyyy/MM/dd/hh/mm/tt).ToString() -replace '\s',''
$uniqe=$uniquedatetime -replace '/',''
$uniq= $uniqe -replace ':',''
$exist=0

#Function to write data to logfile
Function LogWrite
{Param ([string]$logstring)
    Add-content $Lpath -value $logstring
}

#Function to write generated interface data to interface folder
Function testfilewrite ([string]$addstring, [string]$interfacenaam)
{#Check clear uniqueness checkbox to create unique or non-unique csv files
    if($chbClearUniqueness.Checked -eq $false){
        $tspath=$outputpath + "\" + $inf + "\generate" + "\$interfacenaam" + "_$uniq.csv"}
    Else {$tspath=$outputpath + "\" + $inf + "\generate" + "\$interfacenaam" + ".csv"}
    if(!(Test-Path ($outputpath + "\" + $inf + "\generate" + "\" ))){
        New-Item -ItemType directory -Path ($outputpath + "\" + $inf + "\generate" + "\" )}
    Add-content $tspath -value $addstring
}

#Function which removes the current standard testset
function Remove_previous_testset{
$outputpath=$txbOutPath.Text
$Lpath= $outputpath + "\" + "Log\"
        if($cmbInterface.Text -eq 'Interface'){$ltsprogress.Items.Add(' there is no interface selected, cannot remove an empty testset:'+ $tspath)
            return}
            $tspath=$outputpath + "\"+ $cmbInterface.Text + "\generate" + "\"
            $ltsprogress.Items.Add('found:'+ $tspath)
            Get-ChildItem -Path $tspath -Include *.* -Recurse | foreach { $_.Delete()}
            $ltsprogress.Items.Add('remove contents of:'+ $tspath) 
            $ltsprogress.Items.Clear()
            call_clearprogress
}


#Function which removes the current relational testset
function Remove_previous_reltestset{
$outputpath=$txbOutPath.Text
$Lpath= $outputpath + "\" + "Log\"
        if($cmbRelInterface.Text -eq 'Interface'){$lstRelProgress.Items.Add(' there is no interface selected, cannot remove an empty testset:'+ $tspath)
            return}
            $tspath=$outputpath + "\"+ $cmbRelInterface.Text + "\generate" + "\"
            $lstRelProgress.Items.Add('found:'+ $tspath)
            Get-ChildItem -Path $tspath -Include *.* -Recurse | foreach { $_.Delete()}
            $lstRelProgress.Items.Add('remove contents of:'+ $tspath) 
            $lstRelProgress.Items.Clear()
            call_clearprogress
}

#function which tests the given counters on amount so a calculation can be made weather to proceed or not (if the couters are amounts that will create unrealistic testsets)
Function check_counters{
        if(([int]$upd + [int]$amnnok) -gt [int]$amountall ){
            $ltsprogress.Items.Add('The amount of updates and/or NOK is greater then the amount of records, please correct this')
            return}
}
   
#-------------------------------------------------------------------------------------------------------------------
#This section will invoke the interface modules
Function invoke-module-database{
    Param(
    [string]$interface,[string]$part,[string]$records,[string]$new,[string]$update,[string]$nok,[string]$lpath)

    Invoke-Expression -Command "$PSScriptRoot\testsets\module_database.ps1 $interface $part $records $new $update $nok $lpath"
}

Function invoke-module-software{
    Param(
    [string]$interface,[string]$part,[string]$records,[string]$new,[string]$update,[string]$nok,[string]$lpath)

    Invoke-Expression -Command "$PSScriptRoot\testsets\module_software.ps1 $interface $part $records $new $update $nok $lpath"
}

Function invoke-module-DatabaseRelations{
    Param(
    [string]$interface,[string]$part,[string]$records,[string]$new,[string]$update,[string]$nok,[string]$lpath)

    Invoke-Expression -Command "$PSScriptRoot\testsets\module_DatabaseRelations.ps1 $interface $part $records $new $update $nok $lpath"
}

#-------------------------------------------------------------------------------------------------------------------
#Function to count the amount of sources of the chosen interface, this counter will multiply the amount of total records to be created for an interface.
#This function is based on the presumption that on the O: drive a folder named: Controles is present in which will reside the control fle of the chosen interface.
#If a chosen interface has no control file a presumption of 1 (one) source is made
Function countsource ($interface){
 $amntsources=0
 $tempname=Get-ChildItem -Path "O:\Controles" -Filter "ServiceNOW_CMDB_$interface"|Get-ChildItem -Filter "check*"
 if($tempname -eq $null){
    logwrite("No control file of interface: $interface found, assuming count = 1")
    $amntsources=1
    return $amntsources
    break}
 $totalname=$tempname.DirectoryName + "\"+ $tempname.Name
 $imp=Import-Csv $totalname  -Delimiter ';'
            for($i=0;$i -lt $imp.Count;$i++){
                #testfilewrite $imp.filepath[$i]
                if($imp.filepath[$i] -like "*baseline*"){continue} 
                 if($imp.filepath[$i] -like "*tmp*"){continue}
                 if($imp.filepath[$i] -like "*support*"){continue} 
                 if([string]::IsNullOrWhiteSpace($imp.filepath[$i])){continue}
                 else{
                    $amntsources=$amntsources + 1
                }
            }return $amntsources
    }

#-------------------------------------------------------------------------------------------------------------------
# this function groups the creation of testset files for several source interfaces
Function BuildTestset{
    $progressbar.PerformStep()
    switch ($inf)
    {
        Database{LogWrite('Starting creation of testset for interface Database')
            $SourceInterfacePath=$outputpath + "\" + $inf
            $SourceInterfaceTrue= CheckDest $SourceInterfacePath
            if($SourceInterfaceTrue -eq 'True'){
            $progressbar.PerformStep()
            invoke-module-database "dat
            abase supportgroups_db $amnt $anmnw $upd $amnNOK $lpath"
            $progressbar.PerformStep()
            invoke-module-database "database CMDB_SAPLogon_CSV $amnt $anmnw $upd $amnNOK $lpath"
            $progressbar.PerformStep()
            invoke-module-database "database cloud2cmdb $amnt $anmnw $upd $amnNOK $lpath"
            $progressbar.PerformStep()              
            }
        }
        DatabaseRelations{LogWrite('Starting creation of testset for interface Netgear')
            $Relprogressbar.PerformStep()
            invoke-module-DatabaseRelations "DatabaseRelations cloud2cmdb $relRec $relcreate $relDelete $relnok $lpath" 
            $Relprogressbar.PerformStep()
            invoke-module-DatabaseRelations "DatabaseRelations CMDB_SAPLogon_CSV $relRec $relcreate $relDelete $relnok $lpath"  
            $Relprogressbar.PerformStep()                  
            }
        Networkgear{LogWrite('Starting creation of testset for interface Netgear')
            $progressbar.PerformStep()
            invoke-module-DatabaseRelations "Networkgear ecmdb_netgear_its $relRec $relcreate $relDelete $relnok $lpath" 
            $progressbar.PerformStep()
            invoke-module-DatabaseRelations "Networkgear ecmdb_netgear_netco $relRec $relcreate $relDelete $relnok $lpath"  
            $progressbar.PerformStep()
            invoke-module-DatabaseRelations "Networkgear SanQuerySW $relRec $relcreate $relDelete $relnok $lpath" 
            $progressbar.PerformStep()
            invoke-module-DatabaseRelations "Networkgear testfileNetgearPMDiscovery $relRec $relcreate $relDelete $relnok $lpath"  
            $progressbar.PerformStep()                   
            }
        Ports{LogWrite('Starting creation of testset for interface Ports')
            $SourceInterfacePath=$outputpath + "\" + $inf
            $SourceInterfaceTrue= CheckDest $SourceInterfacePath
            if($SourceInterfaceTrue -eq 'True'){
               ecmdb_cisco_mac
               ecmdb_interfaces}
            }
        Server{LogWrite('Starting creation of testset for interface Server')
            $SourceInterfacePath=$outputpath + "\" + $inf
            $SourceInterfaceTrue= CheckDest $SourceInterfacePath
            if($SourceInterfaceTrue -eq 'True'){
                source_server_class_tmp
                $continue=cmdb_ci_server
                $continue=cmdb_autodoc_server
                $continue=sccm_its_ok
                $continue=Source_Orion_ESX_VM
                $continue=Source_Orion_ESX_Hosts
                $continue=uh2_portal_ok}
            }
        KPN_werkplek{LogWrite('Starting creation of testset for interface WPOL')
            }
        Software{LogWrite('Starting creation of testset for interface Software')
                $progressbar.PerformStep()
                invoke-module-software "database supportgroups_sft $amnt $anmnw $upd $amnNOK $lpath" 
                $progressbar.PerformStep()         
                invoke-module-software "software sap-versions $amnt $anmnw $upd $amnNOK $lpath"
                $progressbar.PerformStep()
                invoke-module-software "software CMDB_SAPLogon_CSV $amnt $anmnw $upd $amnNOK $lpath"  
                $progressbar.PerformStep()
            }
        default{LogWrite('The chosen Interface: '+ $inf + ' is not available for creation yet')
            $ltsprogress.Items.Add('The chosen Interface: '+ $inf + ' is not available for creation yet')
            $lstRelProgress.Items.Add('The chosen Interface: '+ $inf + ' is not available for creation yet')
            return
        }
    }
}


#Function to clear the progress screen of the GUI
Function call_clearprogress{
    $ltsprogress.Items.Clear()
    $lstRelProgress.Items.Clear()
    $progressbar.Minimum = 0
    $progressbar.Maximum = 10
    $progressbar.Value = 0
    $relprogressbar.Minimum = 0
    $relprogressbar.Maximum = 10
    $relprogressbar.Value = 0
    #return
}

#Function which will test the sourcepath of the chose interface
Function CheckDest ($SourceInterface) {
    if((Get-ChildItem $SourceInterface|Measure-Object).Count -ge 1){
        LogWrite("Destination has content")
        Return $SourceInterfaceFilled="true"
        }
    Else{
        $ltsprogress.Items.Add('Sourcepath of the interface is invalid, creating it now')
        New-Item -ItemType directory -Path $SourceInterface
        Return $destcontent="false"}
}

#Function to open the logfile when clicked on the 'open logfile' label in the GUI
Function open_logfile{
$outputpath=$txbOutPath.Text
if(!(Test-Path $outputpath)){New-Item -ItemType directory -Path $outputpath}
if(!(Test-Path ($outputpath + "\Log") -PathType Container)){New-Item -ItemType Directory -Path ($outputpath + "\" + $inf + "\Log")}
$Lpath= $outputpath + "\" + "Log\"+ "log_Testset_$SourceInterface" + "_$uniq.log"
if(!(Test-Path $lpath)){$ltsprogress.Items.Add('there is no logfile present')
                        $ltsprogress.Items.Add('please hit the start button after input of parameters for the testset')
    return}
else{
    Invoke-Item $Lpath}
}

#Function to open the testset when clicked on the 'open testset' label in the GUI of the standard interface
Function Open_testset{
    $outputpath=$txbOutPath.Text
    $inf=$cmbInterface.Text
    if($inf -eq 'Interface'){
        $ltsprogress.Items.Add('Please select an interface')
        return}
    $tspath=$outputpath + "\"+ $inf + "\generate\"
    Invoke-Item $tspath
}

#Function to open the testset when clicked on the 'open testset' label in the GUI of the relational interface
Function Open_reltestset{
    $outputpath=$txbOutPath.Text
    $inf=$cmbRelInterface.Text
    if($inf -eq 'Interface'){
        $lstRelProgress.Items.Add('Please select an interface')
        return}
    $tspath=$outputpath + "\"+ $inf + "\generate\"
    Invoke-Item $tspath
}

#This function will call the main process to process a relational interface
function call_rel_start{
#read all input
$inf=$cmbRelInterface.Text
$lstRelProgress.Items.Add('processing Interface '+ $inf)
$relRec=$txbRelRec.Text
$relCreate=$txbRelCreate.Text
$relDelete=$txbRelDeletes.Text
$relnok=$txbRelNan.Text
# add number of new to the number of amount (the base value of record requested times n for n amount of records to be able to count index for n separate sources (which have to be different))

$outputpath=$txbOutPath.Text
#Check_SourcePath $outputpath
if(!(Test-Path $outputpath)){New-Item -ItemType directory -Path $outputpath}
if(!(Test-Path ($outputpath + "\Log") -PathType Container)){New-Item -ItemType Directory -Path ($outputpath + "\" + $inf + "\Log")}
$Lpath= $outputpath + "\" + "Log\"+ "log_Testset_$SourceInterface" + "_$uniq.log"

#check for parameters
if(($inf -eq 'Interface') -or ($relRec -eq '0')){
    $lstRelProgress.Items.Add('please provide parameters')
    return}
#-------------------------------------------------------------------------------------------------------------------
Function countsource ($inf){
 $amntsources=0
 $tempname=Get-ChildItem -Path "O:\Controles" -Filter "ServiceNOW_CMDB_$inf"|Get-ChildItem -Filter "check*"
 if($tempname -eq $null){
    logwrite("No control file of interface: $inf found, assuming count = 1")
    $amntsources=1
    return $amntsources
    break}
 $totalname=$tempname.DirectoryName + "\"+ $tempname.Name
 $imp=Import-Csv $totalname  -Delimiter ';'
            for($i=0;$i -lt $imp.Count;$i++){
                #testfilewrite $imp.filepath[$i]
                if($imp.filepath[$i] -like "*baseline*"){continue} 
                 if($imp.filepath[$i] -like "*tmp*"){continue}
                 if($imp.filepath[$i] -like "*support*"){continue} 
                 if([string]::IsNullOrWhiteSpace($imp.filepath[$i])){continue}
                 else{
                    $amntsources=$amntsources + 1
                }
            }return $amntsources
    }

#check counters
if(([int]$upd + [int]$amnnok) -gt [int]$amnt ){
    $ltsprogress.Items.Add('The amount of updates and/or NOK is greater than the amount of records, please correct this')
    return}
# Main script code
# This script will generate a testset of source an baseline code to the folders of the interface for testing purposes
# Modify date will modify the date fields in the source testdate to today
# Depersonlize will modify potential personal data in the testset to random data
LogWrite('---------------------------------------------------------------------------------------')
LogWrite('Starting creation of testset on ' + $altaltdatelong)
$lstRelProgress.Items.Add('Starting creation of testset on ' + $altaltdatelong)
BuildTestset
$max=countsource
$relprogressbar.Maximum = $max
$relprogressbar.Step = 1
$relprogressbar.Value = 0
LogWrite('Finished creation of testset for on ' + $altaltdatelong)
$lstRelProgress.items.Add('Finished creation of testset  on ' + $altaltdatelong)
$lstRelProgress.items.Add('You can now close this window or start a new creation of a testset')
}


#This function will call the main process to process a standard interface
function call_start{
#read all input
$inf=$cmbInterface.Text
$ltsprogress.Items.Add('processing Interface '+ $inf)
$upd=$txbupdates.Text
$amnt=$txbRecords.Text
$anmnw=$txbNew.Text
$amnnok=$txbnok.Text
# add number of new to the number of amount (the base value of record requested times n for n amount of records to be able to count index for n separate sources (which have to be different))

$outputpath=$txbOutPath.Text
#Check_SourcePath $outputpath
if(!(Test-Path $outputpath)){New-Item -ItemType directory -Path $outputpath}
if(!(Test-Path ($outputpath + "\Log") -PathType Container)){New-Item -ItemType Directory -Path ($outputpath + "\" + $inf + "\Log")}
$Lpath= $outputpath + "\" + "Log\"+ "log_Testset_$SourceInterface" + "_$uniq.log"

#check for parameters
if(($inf -eq 'Interface') -or ($amnt -eq '0')){
    $ltsprogress.Items.Add('please provide parameters')
    return}

#-------------------------------------------------------------------------------------------------------------------
Function countsource ($interface){
 $amntsources=0
 $tempname=Get-ChildItem -Path "O:\Controles" -Filter "ServiceNOW_CMDB_$interface"|Get-ChildItem -Filter "check*"
 if($tempname -eq $null){
    logwrite("No control file of interface: $interface found, assuming count = 1")
    $amntsources=1
    return $amntsources
    break}
 $totalname=$tempname.DirectoryName + "\"+ $tempname.Name
 $imp=Import-Csv $totalname  -Delimiter ';'
            for($i=0;$i -lt $imp.Count;$i++){
                #testfilewrite $imp.filepath[$i]
                if($imp.filepath[$i] -like "*baseline*"){continue} 
                 if($imp.filepath[$i] -like "*tmp*"){continue}
                 if($imp.filepath[$i] -like "*support*"){continue} 
                 if([string]::IsNullOrWhiteSpace($imp.filepath[$i])){continue}
                 else{
                    $amntsources=$amntsources + 1
                }
            }return $amntsources
    }

#check counters
if(([int]$upd + [int]$amnnok) -gt [int]$amnt ){
    $ltsprogress.Items.Add('The amount of updates and/or NOK is greater than the amount of records, please correct this')
    return}
# Main script code
# This script will generate a testset of source an baseline code to the folders of the interface for testing purposes
# Modify date will modify the date fields in the source testdate to today
# Depersonlize will modify potential personal data in the testset to random data
LogWrite('---------------------------------------------------------------------------------------')
LogWrite('Starting creation of testset on ' + $altaltdatelong)
$ltsprogress.Items.Add('Starting creation of testset on ' + $altaltdatelong)
BuildTestset
$max=countsource
$progressbar.Maximum = $max
$progressbar.Step = 1
$progressbar.Value = 0
LogWrite('Finished creation of testset for on ' + $altaltdatelong)
$ltsprogress.items.Add('Finished creation of testset  on ' + $altaltdatelong)
$ltsprogress.items.Add('You can now close this window or start a new creation of a testset')
}

#Call the Function
GenerateForm
